spring:
  datasource:
    url: jdbc:mysql://10.167.98.50:9030/datalab?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Xnysc@ds&2025
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid连接池配置
    druid:
      initialSize: 10
      maxActive: 50
      validationQuery: select 1

sftp:
  region: longjiang
  host: 10.167.98.150
  port: 22
  username: root
  password: JCDZ@rt.0
  remoteDir: /usr/appsoft/iesbase/glyc
  localDownloadDir: ./downloads
  fileStartDate: "2025-10-01"

