spring:
  datasource:
    url: jdbc:mysql://10.217.29.23:9030/datalab?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Xnysc@ds&2025
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid连接池配置
    druid:
      initialSize: 10
      maxActive: 50
      validationQuery: select 1

sftp:
  region: liaoning
  host: 10.97.17.33
  port: 12024
  username: root
  password: lenovo_123456
  remoteDir: /opt/fgl_file
  localDownloadDir: ./downloads
  fileStartDate: "20251001"
