server:
  port: 47601
  servlet:
    context-path: /power-data-collect
  address: 0.0.0.0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  profiles:
    active: prod-neimeng
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: admin1104
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 200
      max-wait: 30000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      keep-alive: true


sftp:
  region: guangxi
