server:
  port: 47601
  servlet:
    context-path: /power-data-collect
  address: 0.0.0.0

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:mysql://10.220.42.139:9030/datalab?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Xnysc@ds&2025
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid连接池配置
    druid:
      initialSize: 10
      maxActive: 50
      validationQuery: select 1

sftp:
  host: 150.30.10.1
  port: 22
  username: sftp
  password: JCDZ@sp.0
  # remoteDir: /home/ies/success
  remoteDir: /home/ies/success
  localDownloadDir: ./downloads
  fileStartDate: "20251001"

app:
  local:
    download:
      dir: ./downloads
