spring:
  datasource:
    url: jdbc:mysql://10.120.66.203:9030/datalab?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Xnysc@ds&2025
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid连接池配置
    druid:
      initialSize: 10
      maxActive: 50
      validationQuery: select 1

sftp:
  region: guangxi
  host: 10.120.66.210
  port: 30001
  username: xnyzh
  password: xnyzh@2026
  remoteDir: /
  localDownloadDir: ./downloads
  fileStartDate: "20251001"

